name: Next.js Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Customize this to your desired deployment branch

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages # The branch name used for GitHub Pages deployment.
          folder: .next/public # The folder containing the built Next.js files for deployment.